name: Docker

on:
  schedule:
    - cron: '35 18 * * *'
  push:
    branches: [ "qa" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "qa" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_REPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run test_unfollow.py
        run: pytest tests/test_unfollow.py

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  deploy:
    name: qa unfollow_user
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_PEM }}
          script: |
            docker stop project_unfollow_user || true
            docker rm project_unfollow_user || true
            docker rmi ${{ secrets.DOCKER_REPO }}:qa || true

            docker pull ${{ secrets.DOCKER_REPO }}:qa

            docker run -d \
              --restart always \
              --name project_unfollow_user \
              -p 8080:8080 \
              -e DBU_HOSTIP=${{ secrets.DBU_HOSTIP }} \
              -e DBU_PORT=${{ secrets.DBU_PORT }} \
              -e DBU_USER=${{ secrets.DBU_USER }} \
              -e DBU_PASSWORD=${{ secrets.DBU_PASSWORD }} \
              -e DBU_NAME=${{ secrets.DBU_NAME }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              ${{ secrets.DOCKER_REPO }}:qa
